// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const nav: string;
export const inner: string;
export const tab: string;
export const tabActive: string;
export const icon: string;
export const label: string;
