// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const nav: string;
export const list: string;
export const item: string;
export const button: string;
export const active: string;
export const icon: string;
export const label: string;
