// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const pageWrapper: string;
export const pageHeading: string;
export const grid: string;
export const heatScaleSection: string;
export const dualSliderWrapper: string;
export const sliderLayer: string;
export const sliderInput: string;
export const heatLabels: string;
export const flavorTypeSection: string;
export const typeToggle: string;
export const activeToggle: string;
