// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const button: string;
export const pink: string;
export const teal: string;
export const icon: string;
export const label: string;
