// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const pageWrapper: string;
export const pageHeading: string;
export const pageSubheading: string;
