// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const hero: string;
export const inner: string;
export const image: string;
export const heading: string;
export const subHeading: string;
