// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const card: string;
export const imageWrapper: string;
export const image: string;
export const title: string;
export const desc: string;
export const gold: string;
export const pink: string;
export const teal: string;
export const purple: string;
