// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const orderForm: string;
export const orderFormGrid: string;
export const orderSummary: string;
export const orderOptions: string;
