// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const categoryFilterSection: string;
export const categoryList: string;
export const categoryButtons: string;
export const active: string;
export const menuSection: string;
export const menuItem: string;
