// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const partyControls: string;
export const active: string;
export const activeDisco: string;
export const discoPulse: string;
