// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const section: string;
export const headerRow: string;
export const heading: string;
export const viewAllButton: string;
export const grid: string;
