// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const headerNav: string;
export const inner: string;
export const navList: string;
export const navItem: string;
