// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const orderSummary: string;
export const itemList: string;
export const item: string;
export const total: string;
export const itemQuantity: string;
export const selectedFlavor: string;
export const price: string;
export const removeButton: string;
