// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const wrapper: string;
export const title: string;
export const subtitle: string;
export const sliderWrapper: string;
export const slider: string;
export const sliderLabels: string;
export const swiperContainer: string;
export const arrowLeft: string;
export const arrowRight: string;
export const track: string;
export const slide: string;
