// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const wrapper: string;
export const image: string;
export const idle: string;
export const idleBounce: string;
export const dance: string;
export const dancePose: string;
export const sparklePop: string;
